import { createApp } from 'vue'
import App from './App.vue'
import router from "./router.js";
import {createPinia} from "pinia";
import naive from 'naive-ui'
import Toast from 'vue-toastification'
import 'vue-toastification/dist/index.css'
import { createI18n } from 'vue-i18n'
import enLocale from './i18n/en.js'
import zhLocale from './i18n/zh.js'
import axios from 'axios'
import { TUIComponents, TUICore, genTestUserSig } from './TUIKit';
// import TUICallKit
import { TUICallKit } from '@tencentcloud/call-uikit-vue';


const app = createApp(App);
const pinia = createPinia();
axios.defaults.baseURL = 'http://127.0.0.1:4523/m1/2418665-0-default';
// http://127.0.0.1:5137
app.config.globalProperties.axios = axios;

const i18n = createI18n({
    locale: 'en',
    messages: {
        en: enLocale,
        zh: zhLocale
    },
    legacy: false
})

router.beforeEach((to, from, next) => {
    if (to.path === '/chat') {
        const SDKAppID = 1400807426; // Your SDKAppID
        const secretKey = 'c5b8e9dad518ccf326e1978d4aedb1c5d80fee9723c8a5710728577fbf501ff3'; //Your secretKey
        const userID = '100031108245'; // User ID


        // init TUIKit
        const TUIKit = TUICore.init({
            SDKAppID,
        });
        // TUIKit add TUIComponents
        TUIKit.use(TUIComponents);
        // TUIKit add TUICallKit
        TUIKit.use(TUICallKit);


        // login TUIKit
        TUIKit.login({
            userID: userID,
            userSig: genTestUserSig({
                SDKAppID,
                secretKey,
                userID,
            }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
        });

        app.use(TUIKit);
        // 在路由进入时动态加载所需内容
        // import('path/to/some/module').then((module) => {
        //     // 执行所需操作
        // });
    }
    next();
});
app.use(router);
app.use(pinia);
app.use(Toast);
app.use(i18n);
app.use(naive);
app.mount('#app')


